use loam_console::Key;

pub(super) fn to_egui(key: Key) -> egui::Key {
    match key {
        Key::Escape => egui::Key::Escape,
        Key::Tab => egui::Key::Tab,
        Key::Backspace => egui::Key::Backspace,
        Key::Enter => egui::Key::Enter,
        Key::Space => egui::Key::Space,
        Key::Delete => egui::Key::Delete,

        Key::ArrowUp => egui::Key::ArrowUp,
        Key::ArrowDown => egui::Key::ArrowDown,
        Key::ArrowLeft => egui::Key::ArrowLeft,
        Key::ArrowRight => egui::Key::ArrowRight,

        Key::Home => egui::Key::Home,
        Key::End => egui::Key::End,
        Key::PageUp => egui::Key::PageUp,
        Key::PageDown => egui::Key::PageDown,

        Key::Backtick => egui::Key::Backtick,
        Key::Minus => egui::Key::Minus,
        Key::Equals => egui::Key::Equals,

        Key::Num0 => egui::Key::Num0,
        Key::Num1 => egui::Key::Num1,
        Key::Num2 => egui::Key::Num2,
        Key::Num3 => egui::Key::Num3,
        Key::Num4 => egui::Key::Num4,
        Key::Num5 => egui::Key::Num5,
        Key::Num6 => egui::Key::Num6,
        Key::Num7 => egui::Key::Num7,
        Key::Num8 => egui::Key::Num8,
        Key::Num9 => egui::Key::Num9,

        Key::A => egui::Key::A,
        Key::B => egui::Key::B,
        Key::C => egui::Key::C,
        Key::D => egui::Key::D,
        Key::E => egui::Key::E,
        Key::F => egui::Key::F,
        Key::G => egui::Key::G,
        Key::H => egui::Key::H,
        Key::I => egui::Key::I,
        Key::J => egui::Key::J,
        Key::K => egui::Key::K,
        Key::L => egui::Key::L,
        Key::M => egui::Key::M,
        Key::N => egui::Key::N,
        Key::O => egui::Key::O,
        Key::P => egui::Key::P,
        Key::Q => egui::Key::Q,
        Key::R => egui::Key::R,
        Key::S => egui::Key::S,
        Key::T => egui::Key::T,
        Key::U => egui::Key::U,
        Key::V => egui::Key::V,
        Key::W => egui::Key::W,
        Key::X => egui::Key::X,
        Key::Y => egui::Key::Y,
        Key::Z => egui::Key::Z,

        Key::F1 => egui::Key::F1,
        Key::F2 => egui::Key::F2,
        Key::F3 => egui::Key::F3,
        Key::F4 => egui::Key::F4,
        Key::F5 => egui::Key::F5,
        Key::F6 => egui::Key::F6,
        Key::F7 => egui::Key::F7,
        Key::F8 => egui::Key::F8,
        Key::F9 => egui::Key::F9,
        Key::F10 => egui::Key::F10,
        Key::F11 => egui::Key::F11,
        Key::F12 => egui::Key::F12,
    }
}

pub(super) fn key_text(key: Key) -> Option<&'static str> {
    match key {
        Key::Backtick => Some("`"),
        Key::Space => Some(" "),
        Key::Minus => Some("-"),
        Key::Equals => Some("="),
        Key::Num0 => Some("0"),
        Key::Num1 => Some("1"),
        Key::Num2 => Some("2"),
        Key::Num3 => Some("3"),
        Key::Num4 => Some("4"),
        Key::Num5 => Some("5"),
        Key::Num6 => Some("6"),
        Key::Num7 => Some("7"),
        Key::Num8 => Some("8"),
        Key::Num9 => Some("9"),
        Key::A => Some("a"),
        Key::B => Some("b"),
        Key::C => Some("c"),
        Key::D => Some("d"),
        Key::E => Some("e"),
        Key::F => Some("f"),
        Key::G => Some("g"),
        Key::H => Some("h"),
        Key::I => Some("i"),
        Key::J => Some("j"),
        Key::K => Some("k"),
        Key::L => Some("l"),
        Key::M => Some("m"),
        Key::N => Some("n"),
        Key::O => Some("o"),
        Key::P => Some("p"),
        Key::Q => Some("q"),
        Key::R => Some("r"),
        Key::S => Some("s"),
        Key::T => Some("t"),
        Key::U => Some("u"),
        Key::V => Some("v"),
        Key::W => Some("w"),
        Key::X => Some("x"),
        Key::Y => Some("y"),
        Key::Z => Some("z"),

        _ => None,
    }
}
